output "storage_account_output" {
  value = {
    id                               = azurerm_storage_account.st.id
    name                             = azurerm_storage_account.st.name
    primary_location                 = azurerm_storage_account.st.primary_location
    secondary_location               = azurerm_storage_account.st.secondary_location
    primary_blob_endpoint            = azurerm_storage_account.st.primary_blob_endpoint
    primary_blob_host                = azurerm_storage_account.st.primary_blob_host
    secondary_blob_endpoint          = azurerm_storage_account.st.secondary_blob_endpoint
    secondary_blob_host              = azurerm_storage_account.st.secondary_blob_host
    primary_queue_endpoint           = azurerm_storage_account.st.primary_queue_endpoint
    primary_queue_host               = azurerm_storage_account.st.primary_queue_host
    secondary_queue_endpoint         = azurerm_storage_account.st.secondary_queue_endpoint
    secondary_queue_host             = azurerm_storage_account.st.secondary_queue_host
    primary_table_endpoint           = azurerm_storage_account.st.primary_table_endpoint
    primary_table_host               = azurerm_storage_account.st.primary_table_host
    secondary_table_endpoint         = azurerm_storage_account.st.secondary_table_endpoint
    secondary_table_host             = azurerm_storage_account.st.secondary_table_host
    primary_file_endpoint            = azurerm_storage_account.st.primary_file_endpoint
    primary_file_host                = azurerm_storage_account.st.primary_file_host
    secondary_file_endpoint          = azurerm_storage_account.st.secondary_file_endpoint
    secondary_file_host              = azurerm_storage_account.st.secondary_file_host
    primary_dfs_endpoint             = azurerm_storage_account.st.primary_dfs_endpoint
    primary_dfs_host                 = azurerm_storage_account.st.primary_dfs_host
    secondary_dfs_endpoint           = azurerm_storage_account.st.secondary_dfs_endpoint
    secondary_dfs_host               = azurerm_storage_account.st.secondary_dfs_host
    primary_web_endpoint             = azurerm_storage_account.st.primary_web_endpoint
    primary_web_host                 = azurerm_storage_account.st.primary_web_host
    secondary_web_endpoint           = azurerm_storage_account.st.secondary_web_endpoint
    secondary_web_host               = azurerm_storage_account.st.secondary_web_host
    primary_access_key               = nonsensitive(azurerm_storage_account.st.primary_access_key)
    secondary_access_key             = nonsensitive(azurerm_storage_account.st.secondary_access_key)
    primary_connection_string        = nonsensitive(azurerm_storage_account.st.primary_connection_string)
    secondary_connection_string      = nonsensitive(azurerm_storage_account.st.secondary_connection_string)
    primary_blob_connection_string   = nonsensitive(azurerm_storage_account.st.primary_blob_connection_string)
    secondary_blob_connection_string = nonsensitive(azurerm_storage_account.st.secondary_blob_connection_string)
  }
}