name: Terraform-Automation
on:
  push:
    branches:
      - main

env:
  version: 1.0.23

jobs:
  Terraform:
    runs-on: self-hosted
    outputs:
      ANSIBLE_HOSTS: ${{ steps.tf.outputs.ANSIBLE_HOSTS }}
    env:
      ARM_USE_MSI: true
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9

    - name: Terraform Init
      run: terraform init #-var-file terraform.dev.tfvars
      working-directory: terraform
    - name: Terraform validate
      run: terraform validate 
      working-directory: terraform
    - name: Terraform plan
      run: terraform plan -out=tfplan #-var-file terraform.dev.tfvars
      working-directory: terraform
    - name: Save Terraform Plan
      run: echo ${{ steps.terraform.outputs.plan }} > tfplan
    
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: terraform

      # - name: Terraform Destroy
      #   run: terraform destroy -var-file variables-dev.tfvars -auto-approve
      #   working-directory: terraform

 